version: '3'

services:
  api:
    build:
      context: .
    volumes:
      - .:/code
      - node_modules:/code/node_modules
    command: "npm start"
    ports:
      - "80:3000"
    restart: always

  doc:
    image: swaggerapi/swagger-ui
    ports:
      - "8080:8080"
    environment:
      SWAGGER_JSON: /code/swagger.yaml
    volumes:
      - .:/code
volumes:
  node_modules:
